version: '3'

services:
    app:
        build: .
        container_name: app
        networks: 
            - app-network
        volumes:
            - app-volume:/var/www

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - app-volume:/var/www
        networks: 
            - app-network    
    
    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "33066:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        networks: 
            - app-network        
                
    redis:
        image: redis:alpine
        expose:
            - 6379
        networks: 
            - app-network    
    
networks: 
    app-network:
        driver: bridge

volumes:
    app-volume: